# Generated by Django 4.1.2 on 2022-10-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('age', models.PositiveIntegerField()),
                ('bio', models.TextField(max_length=500)),
                ('email', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
